version: 2
mergeable:
  - when: pull_request.*
    validate:
      - do: title
        must_exclude:
          regex: ^WIP
        must_include:
          regex: ^((feature|chore|fix)(\(.{1,15}\))?|(HV4086)\-[0-9]{3,5})\:.+$
          message: "Invalid PR title format."
      - do: label
        must_exclude:
          regex: "wip"
    pass:
      - do: checks
        status: "success"
        payload:
          title: "PR is valid 👍"
          summary: "Noice!"
    fail:
      - do: checks
        status: "failure"
        payload:
          title: "Oops! PR is not valid 💩"
